version: '2'

services:
  my-app:
    image: nsdf/catalog:0.1
    env_file:
      - ./.env
    volumes:
      - ./run.py:/nsdf/run.py 
    ports:
      - ${PANEL_PORT}:${PANEL_PORT}
    command: >
      python3 -m panel serve --autoreload --address='0.0.0.0' --allow-websocket-origin='*' --port=${PANEL_PORT} /nsdf/run.py